name: CI
on:
  push:
    branches: [ main, feat-*, ci-* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run typecheck --if-present
      - run: npm run lint:strict
      - run: npm run build
      - run: npm run test:coverage --if-present
