name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # needed to upload release assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Archive dist
        run: |
          mkdir -p out
          cd dist && zip -r ../out/My-Game-Theory-Lab-${GITHUB_REF_NAME}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/My-Game-Theory-Lab-${{ github.ref_name }}.zip
          generate_release_notes: true
